# Generated by Django 4.2.20 on 2025-04-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_fooditems"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hostel_or_office_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="room_or_office_number",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
    ]
