# Generated by Django 4.2.20 on 2025-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Order Received"),
                    ("PREPARING", "Order is being prepared"),
                    ("OUT_FOR_DELIVERY", "Order out for delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="RECEIVED",
                max_length=20,
            ),
        ),
    ]
