# Generated by Django 4.2.20 on 2025-07-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditems",
            name="extras",
            field=models.TextField(blank=True, null=True),
        ),
    ]
