# Generated by Django 4.2.20 on 2025-12-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_shop_alter_fooditems_options_alter_userprofile_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fooditems",
            options={},
        ),
        migrations.RemoveField(
            model_name="fooditems",
            name="shop",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shop",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="shop",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("employee", "Employee"),
                    ("cook", "Cook"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Shop",
        ),
    ]
