# Generated by Django 4.2.20 on 2026-02-19 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shop_alter_fooditems_options_and_more'),
        ('api', '0012_shop_alter_fooditems_options_and_more'),
    ]

    operations = [
    ]
